services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=user_management
      - POSTGRES_USER=omkar
      - POSTGRES_PASSWORD=omkar2002
    ports:
      - "5433:5432"


  redis:
    image: redis:6-alpine
    ports:
      - "6380:6379"


  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"


  web:
    build: .
    command: >
      bash -c "python usermanagement/manage.py makemigrations &&
               python usermanagement/manage.py migrate &&
               python usermanagement/manage.py runserver 0.0.0.0:8000"
    container_name: usermanagementapp
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - mongo


  celery:
    build: .
    command: celery -A usermanagement.celery_app worker --loglevel=info
    working_dir: /app/usermanagement
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db


  celery-beat:
    build: .
    command: celery -A usermanagement.celery_app beat --loglevel=info
    working_dir: /app/usermanagement
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis


volumes:
  postgres_data:
  mongo_data: