# Generated by Django 5.2.2 on 2025-07-01 11:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
